server:
  port: 8080
  context-path: /rabbitmq-provider
spring:
  application:
    name: rabbitmq-service
  # rabbitmq
  rabbitmq:
    host: 172.16.20.165
    port: 5672
    username: o-message-program
    password: o-message-program123!@#qwe
    virtual-host: opnext-server
    publisher-confirms: true #配置发布消息确认回调










